### ISSUE TITLE
Actualizar base de datos inspectores

### ISSUE THREAD

**Issue by tvalzacchi** [elcrisa/geobra#112]
Fede, envío adjunto base de datos inspectores y supervisores, la idea sería cargar inspectores con telefono y mail, para ya poder generarles un usuario. A los coordinadores regionales (supervisores) se le debería agregar el telefono, mail y nombre completo. 

Solo filtre esos 2, el resto de las tareas no los carguemos

**Comment by tvalzacchi** [comment]
[Listado Inspectores (3).xlsx](https://github.com/fhatzen/geobra/files/199965/Listado.Inspectores.3.xlsx)

**Comment by fhatzen** [comment]
@elcrisa habilité la pantalla de inspectores y tomé de esta XLS los e-mail, devuelvo el issue
