### ISSUE TITLE
Tema Reparo

### ISSUE THREAD

**Issue by tvalzacchi** [elcrisa/geobra#127]
El otro día con @elcrisa hablando con la gente de contable quedamos en que se ponga automático el 5 % de reparo, y dejar al lado un SI/NO (por default en NO) con lugar para adjuntar el seguro de caución. Una vez elegido el si y adjuntada la caución, el reparo va en 0

**Comment by fhatzen** [comment]
Estimados, habilité la carga de % predeterminado de reparo a nivel del programa. Al crearse una licitación y elegirse programa se precargará el % del programa. @elcrisa @marcos-zampetti Disiento con el tema de que al adjuntar el seguro y automáticamente se elimine el reparo, yo creo que esto debería hacerse certificado por certificado para garantizar que la validez del seguro está cubriendo adecuadamente el reparo de ese certificado. Por favor evaluar y devolverlo en github aparte
