### ISSUE TITLE
fecha firma comun a todos los lotes

### ISSUE THREAD

**Issue by tvalzacchi** [elcrisa/geobra#130]
La fecha de firma de contrato debe ser la misma para todos los lotes

![fechas firma](https://cloud.githubusercontent.com/assets/17601411/14289197/27a3d1fa-fb30-11e5-9517-694e8e6c8bcf.jpg)

**Comment by marcos-zampetti** [comment]
Ademas no esta tomando la fecha de la firma del contrato, esta tomando la fecha que se carga de Adjudicacion

**Comment by fhatzen** [comment]
Realizados ambos ajustes: fecha contrato es común al expediente y corrección fecha exhibida en listado principal @marcos-zampetti
