### ISSUE TITLE
Certificados aparecen los de otros lotes en Propuestas

### ISSUE THREAD

**Issue by tvalzacchi** [elcrisa/geobra#133]
Fede tomo el caso de la licitacion 31, el certificado del lote 1 aparece en los demas lotes en la parte de propuestas, lo ideal sería que no se vean los certificados en esa solapa y solamente en la de Certificados
@elcrisa 

![image](https://cloud.githubusercontent.com/assets/17601411/14318103/b788a712-fbe1-11e5-9c8d-34233b682dbc.png)

**Comment by tvalzacchi** [comment]
Tambien aparecen en _ver adjuntos_ y en solapa Documentos, sería ideal que solo se vea el de ese lote y no del resto

**Comment by fhatzen** [comment]
Se corrigió este error lógico, los certificados aparecerán solamente en la licitación / lote a la que corresponden y sólo en la solapa de certificados, documentos y adjuntos
