### ISSUE TITLE
Menu desplegable

### ISSUE THREAD

**Issue by marcos-zampetti** [elcrisa/geobra#138]
En la pestaña contratista cuando queres seleccionar el que gano, aparece este listado y solo deberían aparecer los que están en la pestaña anterior con sus respectivos montos.
![imagen 1](https://cloud.githubusercontent.com/assets/18214286/14325529/2074698c-fc00-11e5-95d7-3afe710ce27a.jpg)

**Comment by fhatzen** [comment]
resuelto este error
