### ISSUE TITLE
Fechas

### ISSUE THREAD

**Issue by marcos-zampetti** [elcrisa/geobra#140]
Fede la fecha de apertura de ofertas aparece en 3 pestañas, esta que va con la imagen debería tomarse de la pestaña llamado cuando subis el acata de apertura de ofertas, igual que en la pestaña fechas. Solo que las muestre. Y que una ves subido en un lote lo replique en todos los que haya.
![imagen 1](https://cloud.githubusercontent.com/assets/18214286/14326075/ab9d234e-fc02-11e5-9d7c-d9758c8a4a9c.jpg)

**Comment by fhatzen** [comment]
Buenos detalles Marcos! supongo son para mí, tenés que marcarme como asignado en ese caso, pregunta a la gente de allá cómo se hace, por favor @elcrisa @tvalzacchi

**Comment by fhatzen** [comment]
Realizado este ajuste @tvalzacchi @marcos-zampetti : al subir documentos de estados 30, 42, 50, 74 se alimentan las fechas de los respectivos campos siendo fecha apertura (30), adjudicación (42) y contrato (50) comunes a todos los lotes y fecha inicio (74, en ejecución) propia de cada licitación
