### ISSUE TITLE
Licitaciones destacadas por usuario

### ISSUE THREAD

**Issue by tvalzacchi** [elcrisa/geobra#142]
Fede, por reiterados pedidos de German, tendríamos que pensar en una forma de poder destacar una licitación por usuario. Por ahora solo te pedimos eso, y que se puedan ver en el listado, después vemos como lo configuramos en la pantalla de inicio. Esto solo lo vería cada usuario. No lo tomes como prioridad, pero tenelo en cuenta

**Comment by fhatzen** [comment]
Realizado este requerimiento @elcrisa
