### ISSUE TITLE
Documentos obligatorios

### ISSUE THREAD

**Issue by tvalzacchi** [elcrisa/geobra#143]
Fede, nosotros seguimos ampliando la base de documentos que nos diste a crear. Una columna que nos parece útil además de los cambios mencionados en el #105 , sería poder seleccionar si es un documento OBLIGATORIO o  NO. También estaría bueno poder seleccionar de cada documento, con tildes a que programas pertenece. Eso daría bastante flexibilidad y creo q podríamos aportar más nosotros desde este lado, sin tener que joderte sobre que modificar en cada programa

**Comment by tvalzacchi** [comment]
@elcrisa

**Comment by fhatzen** [comment]
En configuración - documentos se agregó campo "obligatorio" para marcar obligatoriedad y también la posibilidad de indicar a qué programas pertenece el documento y de subir el documento predeterminado (Aprovecho para comentar que a la inversa, desde cada programa se puede especificar qué documentos contiene y subir el adjunto predeterminado) @elcrisa @marcos-zampetti
