### ISSUE TITLE
Estados Plan de obras

### ISSUE THREAD

**Issue by tvalzacchi** [elcrisa/geobra#145]
Fede, te envío la versión del archivo de Estados para el Plan de Obras. 

@elcrisa 
[ESTADOS PLAN DE OBRAS-001.xlsx](https://github.com/elcrisa/geobra/files/209039/ESTADOS.PLAN.DE.OBRAS-001.xlsx)

**Comment by tvalzacchi** [comment]
Ya tendríamos que ir por todos los estados. Tendríamos que ya poder ver estos estados en G-Obra, y en el mapa

**Comment by fhatzen** [comment]
Completada la base de datos, tabla estados con los recibidos. Para que aparezcan en el mapa tenemos que negociar con @lfantone que el mapa comience a embeber los datos vivos.

Aprovecho @lfantone para pasarte la tabla de estados al día de hoy, fijate por favor si podés ajustar los colores a los que manejamos en las tablas, te genero un issue aparte

20	Elegibilidad	#FFFFFF
26	Proyecto ejecutivo	#40E0D0
30	Llamada	#40E0D0
40	Evaluación de las propuestas	#40E0D0
41	Preadjudicada	#40E0D0
42	Adjudicada	#40E0D0
50	Contratada	#40E0D0
74	En Ejecución	#9ACD32
82	Plazo de garantía	#8D38C9
100	Con recepción definitiva	#8D38C9
