### ISSUE TITLE
Fecha Recepción Provisoria y Fecha Recepción Definitiva son parte del lote (no deberia decir licitacion) y no del expediente.

### ISSUE THREAD

**Issue by elcrisa** [elcrisa/geobra#151]
![image](https://cloud.githubusercontent.com/assets/17600443/14412081/5e0d3660-ff30-11e5-91d8-aa8d22b1ffa5.png)

**Comment by fhatzen** [comment]
Hecho, las fechas de recepción volvieron al lote y se cambió el nombre del apartado por "Lote"
