### ISSUE TITLE
ERROR en carga de nueva licitacion

### ISSUE THREAD

**Issue by elcrisa** [elcrisa/geobra#162]
No permite crear una nueva licitacion por que avisa de que ya existe ese numero, este accionar es correcto siempre que ambas esten dentro de un mismo programa (ej: Frec) pero en este caso esta en otro programa (INET) de modo que deberia permitirlo.
![image](https://cloud.githubusercontent.com/assets/17600443/14468857/245ddd96-00b8-11e6-9921-7ec9cb289e9f.png)

**Comment by elcrisa** [comment]
para poder crearla la pase a 999/16 de INET, pero deberia ser la 1/16.

**Comment by fhatzen** [comment]
no era un ERROR sino una modificación, quedó realizada esta modificación
