### ISSUE TITLE
Problemas Mapa

### ISSUE THREAD

**Issue by renato2424** [elcrisa/geobra#164]
En el mapa Tardan mucho en aparecer las escuelas y a veces no aparecen.
En cambio en qa.g-obra.com no aparecen nunca.
En el recuadro de detalles (cuando se hace click sobre una escuela) deben aparecer los montos con separadores de miles usando la coma (,) y los separadores de decimales usando el punto (.) para tener una coerencia con las pantallas del programa.
Gracias

**Comment by fhatzen** [comment]
En qa.g-obra.com no aparecen las escuelas en el mapa porque las obras que
están cargadas en QA están asociadas a la escuela "A asignar". Esto es
porque estamos haciendo pruebas de datos con un XLS lamentable que nos
tiran por la cabeza.

2016-04-13 11:53 GMT-03:00 Rene Sourigues <notifications@github.com>:

**Comment by lfantone** [comment]
@fhatzen Querés que filtre los datos así no tenemos este tipo de problemas ?

**Comment by fhatzen** [comment]
Luciano: en realidad veo que el filtrado debería nacer en el XML,
excluyendo todo lo que no tenga valor en X e Y. Ya lo hice y empezará a
tener efecto en cuanto se haga el git pull (si te referías a otra cosa por
favor aclarame, de lo contrario creo que se puede cerrar el issue)

2016-04-13 13:47 GMT-03:00 Luciano Fantone <notifications@github.com>:

**Comment by lfantone** [comment]
@fhatzen me refería a eso mismo.
Cierro el issue entonces.
