### ISSUE TITLE
Listado Completo

### ISSUE THREAD

**Issue by marcos-zampetti** [elcrisa/geobra#165]
Fede el listado completo esta ordenando por licitación y por lo tanto si hay mas de un lote y mas de un programa con ese numero de licitacio, pasa lo que esta en la imagen:
![pantalla](https://cloud.githubusercontent.com/assets/18214286/14502899/f0282c58-0183-11e6-9bbb-d9bdb9590652.jpg)

**Comment by fhatzen** [comment]
Quedó resuelto el orden predeterminado de listados
