### ISSUE TITLE
adición de rubros en C y P contratado

### ISSUE THREAD

**Issue by tvalzacchi** [elcrisa/geobra#35]
Que puedan tener la opción de agregar rubros no previstos en el oficial (en las FREC vimos que suelen pedir en las memorias cosas que no estan previstas en el computo oficial, y también para poder hacer una mayo apertura). Que sea un boton que diga **agregar rubros no previstos**

**Comment by tvalzacchi** [comment]
no digo de agregar rubros que no esten en el listado de rubros existente, sino de poder generar items en rubros que no estaban en la CyP oficial

**Comment by tvalzacchi** [comment]
Fede, lo que ahora vemos como priioritario sería poder cambiar la unidad de medida y la cantidad en el contratado en referencia con el original

**Comment by elcrisa** [comment]
NO es necesario este ISSUE, era para las Frec y no fue utilizado
